[webservers:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file="../../Pathnex-ec2-key.pem"  #  Change with your Key location
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers]
Pathnex-server ansible_host=3.109.200.9 # Change with the Public IP of your ec2 (visible in tf output)

